name: Build JDP Android
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Briefcase
        run: pip install briefcase
      - name: Build APK
        run: briefcase package android --no-sign
